name: Testing

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.11.1']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Echo debug information
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: |
          pwd
          echo "==================================="
          ls -la
          echo "==================================="
          echo "Node version: $(node --version)"
          echo "==================================="
          echo "Npm version: $(npm --version)"
          echo "==================================="
          env
      # - name: Install dependencies
      #   if: steps.setup-node.outputs.cache-hit != 'true'
      #   run: npm ci
      # - name: Build the project
      #   run: npm run build
      # - name: Run jest
      #   run: npm run test
      # - name: Run tsd
      #   run: npm run test-dts-only
